export const buses = [
  {
    id: 1,
    name: "Laxmi Holidays",
    type: "Volvo 9600 A/C Semi Sleeper (2+2)",
    departure: "18:30",
    duration: "03h 40m",
    arrival: "22:10",
    rating: 4.0,
    price: 499,
    seatsAvailable: 33,
    departureLocation: "Delhi",
    destinationLocation: "Hyderabad",
    amenities: ["WiFi", "Charging Point", "Blanket", "Water Bottle"],
  },
  {
    id: 2,
    name: "RS Yadav Smart Bus",
    type: "Volvo 9600 A/C Semi Sleeper (2+2)",
    departure: "21:15",
    duration: "03h 55m",
    arrival: "01:10",
    rating: 3.4,
    price: 499,
    seatsAvailable: 5,
    departureLocation: "Delhi",
    destinationLocation: "Jaipur",
    amenities: ["Charging Point", "Blanket", "Water Bottle"],
  },
  {
    id: 3,
    name: "Sharma Travels",
    type: "Scania Multi-Axle A/C Sleeper (2+1)",
    departure: "23:00",
    duration: "07h 20m",
    arrival: "06:20",
    rating: 4.5,
    price: 899,
    seatsAvailable: 10,
    departureLocation: "Mumbai",
    destinationLocation: "Pune",
    amenities: ["WiFi", "Charging Point", "Water Bottle"],
  },
  {
    id: 4,
    name: "VRL Travels",
    type: "Mercedes Benz Multi-Axle A/C Sleeper (2+1)",
    departure: "20:00",
    duration: "05h 50m",
    arrival: "01:50",
    rating: 4.7,
    price: 1199,
    seatsAvailable: 15,
    departureLocation: "Bangalore",
    destinationLocation: "Hyderabad",
    amenities: ["WiFi", "Charging Point", "Blanket", "Water Bottle"],
  },
  {
    id: 5,
    name: "SRS Travels",
    type: "Non-AC Seater/Sleeper (2+1)",
    departure: "17:45",
    duration: "06h 30m",
    arrival: "00:15",
    rating: 3.8,
    price: 699,
    seatsAvailable: 8,
    departureLocation: "Chennai",
    destinationLocation: "Coimbatore",
    amenities: ["Charging Point", "Water Bottle"],
  },
  {
    id: 6,
    name: "Orange Tours & Travels",
    type: "Volvo A/C Sleeper (2+1)",
    departure: "22:30",
    duration: "08h 10m",
    arrival: "06:40",
    rating: 4.6,
    price: 999,
    seatsAvailable: 20,
    departureLocation: "Hyderabad",
    destinationLocation: "Vijayawada",
    amenities: ["WiFi", "Charging Point", "Blanket", "Water Bottle"],
  },
  {
    id: 7,
    name: "Kaveri Travels",
    type: "AC Sleeper (2+1)",
    departure: "19:00",
    duration: "04h 45m",
    arrival: "23:45",
    rating: 4.1,
    price: 799,
    seatsAvailable: 12,
    departureLocation: "Delhi",
    destinationLocation: "jaipur",
    amenities: ["Charging Point", "Blanket"],
  },
  {
    id: 8,
    name: "Parveen Travels",
    type: "Non-AC Seater (2+2)",
    departure: "16:30",
    duration: "06h 50m",
    arrival: "23:20",
    rating: 3.5,
    price: 599,
    seatsAvailable: 25,
    departureLocation: "Kolkata",
    destinationLocation: "Digha",
    amenities: ["Charging Point", "Water Bottle"],
  },
];
